### ISSUE TITLE
Consider database index on created_at column of the rmp_profiled_requests table

### ISSUE THREAD

**Issue by kobaltz** [hschne/rails-mini-profiler#1]
### Is your proposal related to a problem?

No

### Describe the solution you'd like

As the tables grow for Rails Mini Profiler, there could be a lot to clean up after a given month has gone by. The clean up job referenced in the README suggests to query the ProfiledRequest table and destroy the records.

```
RailsMiniProfiler::ProfiledRequest.where('created_at < ?', 1.month.ago).destroy_all
```

Depending on the application's traffic, this could end up being a very expensive database query.

**Comment by hschne** [comment]
Excellent idea, I 100% agree with your assessment :+1: 

I'd love if you were to open a pull request to add that index. 
- Update `db/migrate/20210621185018_create_rmp.rb`
- Update `spec/dummy/db/schema.rb` accordingly

If you don't have the time that's  alright, I'll get around to it sooner or later :)
