### ISSUE TITLE
Error on RailsMiniProfiler::Badge trying to render the badge on a redirect response

### ISSUE THREAD

**Issue by cpgo** [hschne/rails-mini-profiler#115]
Rails 6.1.4.1
ruby 2.7.3p183

Hi, I am facing an error on the following line on one of my company apps https://github.com/hschne/rails-mini-profiler/blob/069f9faf0c9843b1b1be5bef70660580bb2598c0/lib/rails_mini_profiler/badge.rb#L49

Looks like the middleware is trying to write the badge to a redirect response that does not responds to the method `.body`
```
@original_response.response
["<html><body>You are being <a href=\"http://localhost:3000/some_route\">redirected</a>.</body></html>"]
```

Maybe the problem is on the app internals and not on the profiler middleware, for now I monkey patched the method with the following guard clause
```diff
    def modified_body
+     return unless @original_response.response.respond_to?(:body)

      body = @original_response.response.body
      index = body.rindex(%r{</body>}i) || body.rindex(%r{</html>}i)
      if index
        body.dup.insert(index, badge_content)
      else
        body
      end
    end
```
I will try to find out why our redirect is not a proper rack object and setup a reproducible repo if its apropriate

**Comment by hschne** [comment]
Hey @cpgo! Thanks for the bug report!

That's interesting. I could imagine that all redirects cause this error, but if you had any steps to reproduce this that would still be awesome! :raised_hands:

**Comment by cpgo** [comment]
Hi @hschne I'm a bit busy today but will try to create something in the next days.
Thank you

**Comment by hschne** [comment]
@cpgo I could not reproduce this, unfortunately, so I did the next best thing and basically ported your monkey patch :wink: 

Rails mini profiler will now ignore responses that don't respond to body and not try to inject a badge into those.

**Comment by cpgo** [comment]
Hi @hschne, I tried  reproducing with a simple redirection from devise but no luck.
We must have a weird middleware on this application, I couldnt track it yet because its a huge codebase
