### ISSUE TITLE
Getting uninitialized constant RailsMiniProfiler::Storage::Memory (NameError)

### ISSUE THREAD

**Issue by enderahmetyurt** [hschne/rails-mini-profiler#13]
Found a bug? Please fill out the sections below! 👍

### Issue Summary

Getting `uninitialized constant RailsMiniProfiler::Storage::Memory (NameError)` error when getting start rails-mini-profile

### Steps to Reproduce

1. add `gem 'rails_mini_profiler'` to Gemfile
2. run `bundle install`
3. run `rails rails_mini_profiler:install`
4. getting error `project_path/initializers/rails_mini_profiler.rb:9:in block in <main>: uninitialized constant RailsMiniProfiler::Storage::Memory (NameError)`

### Technical details

* Rails version: 6.1.4
* Ruby version: 2.7.2

**Comment by hschne** [comment]
Thanks for your bugreport! :+1: 

Terribly sorry about that. This is a known issue, I described a quick fix in #5. Let me know if that helps :slightly_smiling_face:

**Comment by enderahmetyurt** [comment]
it's working now thank you but I have a different problem now :) https://github.com/hschne/rails-mini-profiler/issues/14
