### ISSUE TITLE
Getting error undefined local variable or method `view_context'

### ISSUE THREAD

**Issue by enderahmetyurt** [hschne/rails-mini-profiler#14]
When I clickt he little hedgehog 🦔  on the top left, I get error `Getting error undefined local variable or method `view_context'`

details of the error:

NameError in RailsMiniProfiler::ProfiledRequestsController#show
```
rails_mini_profiler (0.1.1) app/controllers/rails_mini_profiler/application_controller.rb:13:in `present'
rails_mini_profiler (0.1.1) app/controllers/rails_mini_profiler/profiled_requests_controller.rb:22:in `block in show'
```

### Steps to Reproduce

1. Do all thing from installation
2. Add ` mount RailsMiniProfiler::Engine => '/rails_mini_profiler'` to `routes.rb`
3. Restart rails server

### Technical details

* Rails version: 6.1.4
* Ruby version: 2.7.2
* This a Rails API project

**Comment by hschne** [comment]
Thanks for your bugreport! :raised_hands: 

I already merged a fix, if you want to give it a try (and not wait for another release), please modify your Gemfile like so: 

```ruby
gem "rails_mini_profiler", git: "https://github.com/hschne/rails-mini-profiler"
```

Additionally, I updated the readme with some information on additional measures you may have to take to get Rails Mini Profiler running in your API-only app. See [here](https://github.com/hschne/rails-mini-profiler#support-for-api-only-apps). 

Let me know how it goes! I'd love to get more feedback from you to better support API-only apps :slightly_smiling_face:

**Comment by enderahmetyurt** [comment]
thank you @hschne it's working now. I just want to say, Gemfile should be like this

```ruby
gem "rails_mini_profiler", git: "https://github.com/hschne/rails-mini-profiler", branch: 'main'
```

I will share my experience about it on API only app 😉
