### ISSUE TITLE
Profiling file upload produces a "string contains null byte" argument error

### ISSUE THREAD

**Issue by Qapybara28** [hschne/rails-mini-profiler#157]
### Issue Summary

Multipart request body when uploading a file contains NULL bytes and the following error occurs when persisting the instance of ProfiledRequest on postgresql.

```
Rails -- Exception: ArgumentError: string contains null byte
```

### Steps to Reproduce

1. Monitor a file upload with rails-mini-profiler 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

It should handle this case properly without crashing.

### Dirty workaround

config/environments/development.rb:

```ruby
config.to_prepare do
    RailsMiniProfiler::ProfiledRequest.class_eval do
      before_save do
        self.request_body = request_body.to_s
                                        .encode('UTF-8', invalid: :replace, undef: :replace)
                                        .delete("\000")
      end
    end
  end
```

Edit: Fix typos

**Comment by hschne** [comment]
> It should handle this case properly without crashing.

I agree :grin: 

Thanks for the great description and workaround, really helps with debugging. I'll take a look :+1:

**Comment by Qapybara28** [comment]
To be exhaustive: Same problem arise when sending binary content in the response (pdf, etc.)

**Comment by Qapybara28** [comment]
As mentionned above, the response body should be sanitized as well. Should I create a new issue ?

**Comment by hschne** [comment]
@Qapybara28 My bad, reading is hard. I created a new issue for that, and will tackle that ASAP - unless you want to create a PR yourself :wink:

Thanks a lot for bringing it up! :raised_hands:
