### ISSUE TITLE
Vendor data present in the most recent release

### ISSUE THREAD

**Issue by mensfeld** [hschne/rails-mini-profiler#33]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using WhiteSource https://Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? It wasn't there previously. Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

0.2.0 is now 38 times bigger than 0.1.3

A lot of Ruby code seems to be committed: in `vendor/bundle/ruby/3.0.0/`

ref: https://rubygems.org/gems/rails_mini_profiler

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by mensfeld** [comment]
Wow that was quick!

**Comment by hschne** [comment]
Thanks for raising this issue! 

Definitely not intended. Do you have a hint why including vendor in the spec files like so would result in a `bundle` folder being included there as well? Not really sure where that would be coming from :sweat_smile: 

```ruby
spec.files = Dir['{app,config,db,lib,public,vendor}/**/*', 'MIT-LICENSE', 'Rakefile', 'README.md']
```

In any case, I'll publish a new release ASAP :)

**Comment by mensfeld** [comment]
> Do you have a hint why including vendor in the spec files like so would result in a bundle folder being included there as well?

No idea ;) I look for anomalies and do my best to report them to the maintainers but the reasons, why things happen, are harder for be to figure out. I can look into that tomorrow if you need help though.
