### ISSUE TITLE
ActiveModel::RangeError - 40190805895 is out of range for ActiveModel::Type::Integer with limit 4 bytes

### ISSUE THREAD

**Issue by kivanio** [hschne/rails-mini-profiler#6]
ActiveModel::RangeError - 40190805895 is out of range for ActiveModel::Type::Integer with limit 4 bytes

You need change integer types to bigint at migration template.

**Comment by hschne** [comment]
Thanks for raising this issue! 

Could you point me to which attribute is most likely responsible? Probably it's all of those, correct? 

```
t.integer :start
t.integer :finish
t.integer :duration
t.integer :allocations
```

I'd be happy to merge any PRs, if you want to open any :wink:
