### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by leastbad** [hschne/rails-mini-profiler#8]
### Is your proposal related to a problem?

This library looks amazing, but for those of us who won't touch sprockets at a distance, the lack of a build pipeline option is a blocking issue.

### Describe the solution you'd like

rails-mini-profiler should offer an npm package version of the assets.

### Describe any alternatives you've considered

The alternative is not using the library, sadly.

### Additional context

Pretty please?

**Comment by hschne** [comment]
> Pretty please?

Well, if you ask like that :stuck_out_tongue: 

Webpack support is _definitely_ coming. For the next couple of releases, I'm planning on fixing some bugs, and improving the UI. Improving the UI means more interactivity, thus more Javascript, and there is no way I'm gonna keep fidgeting plain JS and the asset pipeline forever. Sooner or later I'll have to move things into an NPM package.   

So yeah. No ETA, but it's on on the horizon. Somewhere :sunrise:

**Comment by leastbad** [comment]
I'm tempted to say that I'd help, but I know from experience that this task is opinionated and fussy. 

I hope that you'll comment here if an npm package debuts! It really does look like an amazing and much needed library.

**Comment by hschne** [comment]
@leastbad The latest release _should_ make Rails Mini Profiler usable for people who don't use sprockets/the asset pipeline.

I created a [NPM package](https://www.npmjs.com/package/@rails-mini-profiler/assets) which contains the assets. I would love if you could give this a try. Let me know how it goes! :raised_hands:

**Comment by leastbad** [comment]
Sorry for the delay! Thanks for doing this.

It does seem like it's assuming Sprockets is in scope:
```
         1: from /home/leastbad/.rvm/gems/ruby-2.7.3/gems/rails_mini_profiler-0.3.0/lib/rails_mini_profiler/engine.rb:15:in `block in <class:Engine>'
/home/leastbad/.rvm/gems/ruby-2.7.3/gems/railties-6.1.4/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000055fc3206cb68> (NoMethodError)
Did you mean?  asset_host
```

**Comment by hschne** [comment]
Welp. Well, thanks for giving this a try :raised_hands: 

Not sure how this one slipped through. I guess you tried this with `rails new --no-sprockets`? :thinking:

**Comment by leastbad** [comment]
I will keep trying whatever you suggest, and hopefully with faster turnaround. Juggling lots of balls, but I am excited for this tool. Plus: I asked for it, the least I can do is follow through.

I'm one of the many who walked away from Sprockets the moment Webpacker became available, and haven't looked back. There's no trace of it in any of our apps.

**Comment by hschne** [comment]
Alright, thanks a lot! Don't worry about the turnaround times :wink: 

I'll let you know when there's an update!
