### ISSUE TITLE
Update README usage section

### ISSUE THREAD

**Issue by kenzo-tanaka** [hschne/rails-mini-profiler#93]
Hi! 
I found this gem in GitHub explore, it's nice one😁 

### Is your proposal related to a problem?

(Provide a clear and concise description of what the problem is.)

I think the `RailsMiniProfiler::Engine` should be mounted in the development environment only.  So I think It is a good idea to update the README that way as well. 

### Describe the solution you'd like

(Provide a clear and concise description of what you want to happen.)

How about updating usage section as follows?

```ruby
# routes.rb
Rails.application.routes.draw do
  ...

  mount RailsMiniProfiler::Engine => '/rails_mini_profiler' if Rails.env.development?
end
```

like [letter_opener_web](https://github.com/fgrehm/letter_opener_web#usage)

### Describe any alternatives you've considered

(Let us know about other solutions you've tried or researched.)

### Additional context

(Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.)

**Comment by hschne** [comment]
Thanks a lot for your request! Glad to hear you enjoy this gem :blush: 

The thing about RMP is that is actually _intended_ to be used both in production as well as your local development environment. Similar to rack mini profiler, profiling is available in production per default, but requests that you want to profile need to be whitelisted. 

This is to avoid impacting performance for your end-users negatively, while still giving developers the option to perform some profiling in production. [Profiling in Production](https://github.com/hschne/rails-mini-profiler#profiling-in-production) should explain this in more detail I hope...

Do you have suggestions on how to improve the documentation to bring that across better? :thinking:

**Comment by kenzo-tanaka** [comment]
@hschne 

Thank you for your thoughtful answer! 

> The thing about RMP is that is actually intended to be used both in production as well as your local development environment.

Sorry, I misunderstood about these things.

I was worried that anyone could access `/rails_mini_profiler` in the production environment by default, but I see that RMP is disabled in the production environment by the default [configuration](https://github.com/hschne/rails-mini-profiler#configuration).
I had overlooked that 😅

I think the README is clear enough now! 
It might be clearer if it's written that `/rails_min_profiler` is only accessible in the development environment by default.

**Comment by hschne** [comment]
@kenzo-tanaka Sooo, inspired by your request I did some testing and found some pretty severe bugs related to authentication/authorization in Production. Big thanks for pointing me that way! :grin: 

I made some fixes and updated the Readme section about production profiling a bit. I believe it is a bit clearer now.

**Comment by kenzo-tanaka** [comment]
@hschne Thank you for comment! I'm glad I could help 😁
